# Generated by Django 3.2 on 2023-07-06 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='captcha',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
