# Generated by Django 3.2 on 2023-07-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230706_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptchaField',
        ),
        migrations.AlterField(
            model_name='user',
            name='captcha',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
