# Generated by Django 3.2 on 2023-07-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230707_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='captcha',
        ),
    ]
