# Generated by Django 3.2 on 2023-07-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_captcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='captcha',
            field=models.CharField(default='captcha', max_length=10),
        ),
    ]
