# Generated by Django 3.2 on 2023-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_captchafield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='captcha',
            field=models.CharField(default='', max_length=10),
        ),
    ]
